"""
scorer.py — Confidence fusion and transparency label generation.

Formula:
    ai_probability = (0.60 × llm_score) + (0.40 × stylo_score)

Thresholds (intentionally conservative — false positives hurt real creators):
    ai_probability ≥ 0.80  →  classification="ai",        confidence_level="high"
    ai_probability ≤ 0.20  →  classification="human",     confidence_level="high"
    otherwise              →  classification="uncertain",  confidence_level="uncertain"
"""

from config import LLM_WEIGHT, STYLO_WEIGHT, AI_HIGH_THRESHOLD, HUMAN_HIGH_THRESHOLD

# ---------------------------------------------------------------------------
# Label text (verbatim strings referenced in spec + README)
# ---------------------------------------------------------------------------

LABEL_AI_HIGH = """\
⚠️ AI-Generated Content
Our analysis strongly suggests this work was generated by an AI writing tool, not \
written by the credited creator. Confidence: High. If you are the creator and believe \
this is incorrect, you may contest this classification using the appeals process.\
"""

LABEL_HUMAN_HIGH = """\
✅ Human-Authored
Our analysis strongly suggests this work was written by the credited creator. \
Confidence: High.\
"""

LABEL_UNCERTAIN = """\
🔍 Authorship Uncertain
Our system could not confidently determine whether this work was written by a human \
or generated by AI. This may reflect an unusual writing style, a short submission, \
or signals that disagree. The creator may contest this classification. This label \
may be updated following a review.\
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def fuse(llm_score: float, stylo_score: float) -> float:
    """Return weighted ai_probability ∈ [0, 1]."""
    return round(LLM_WEIGHT * llm_score + STYLO_WEIGHT * stylo_score, 4)


def classify(ai_probability: float) -> tuple[str, str]:
    """Return (classification, confidence_level)."""
    if ai_probability >= AI_HIGH_THRESHOLD:
        return "ai", "high"
    if ai_probability <= HUMAN_HIGH_THRESHOLD:
        return "human", "high"
    return "uncertain", "uncertain"


def label(classification: str, confidence_level: str) -> str:
    """Return the transparency label string for display to users."""
    if classification == "ai" and confidence_level == "high":
        return LABEL_AI_HIGH
    if classification == "human" and confidence_level == "high":
        return LABEL_HUMAN_HIGH
    return LABEL_UNCERTAIN